import { TABLES } from "../schema.js";

const tableNames = new Set(Object.keys(TABLES));
const columnNames = new Set(Object.values(TABLES).flatMap((t) => Object.keys(t.columns)));
const tokenPattern = /'(?:''|[^'])*'|"(?:""|[^"])*"|--[^\n]*|\/\*[\s\S]*?\*\/|\b[A-Za-z_][A-Za-z_0-9]*\b|\?/g;

export function validateSchema(schema) {
  if (!/^[a-z_][a-z_0-9]{0,62}$/.test(schema)) throw new Error("Invalid PostgreSQL application schema");
  return schema;
}

// The existing repositories use a small, fixed SQL vocabulary. Keep literals
// intact, parameterize values, and quote identifiers to preserve camelCase rows.
export function postgresSql(sql, schema) {
  validateSchema(schema);
  if (/\b(?:PRAGMA|ATTACH|DETACH|sqlite_master)\b/i.test(sql)) {
    throw new Error("SQLite-only operation is unavailable on PostgreSQL");
  }
  const replace = sql.match(/^\s*INSERT OR REPLACE INTO (\w+)\s*\(([^)]+)\)/i);
  if (replace) {
    const table = replace[1];
    if (!tableNames.has(table)) throw new Error("Unsupported PostgreSQL upsert table");
    const columns = replace[2].split(",").map((c) => c.trim());
    const keys = table === "kv" ? ["scope", "key"] : ["id"];
    const updates = columns.filter((c) => !keys.includes(c));
    sql = sql.replace(/INSERT OR REPLACE/i, "INSERT").replace(/;\s*$/, "");
    sql += ` ON CONFLICT (${keys.join(", ")}) DO UPDATE SET ${updates.map((c) => `${c} = excluded.${c}`).join(", ")}`;
  }
  let parameter = 0;
  return sql.replace(tokenPattern, (token) => {
    if (token === "?") return `$${++parameter}`;
    if (tableNames.has(token)) return `"${schema}"."${token}"`;
    if (columnNames.has(token)) return `"${token}"`;
    if (token === "REAL") return "DOUBLE PRECISION";
    return token;
  }).replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
}
