import { describe, it, expect } from 'vitest';
import { postgresSql, validateSchema } from '../../src/lib/db/adapters/postgresSql.js';
import { TABLES, buildCreateTableSql } from '../../src/lib/db/schema.js';

describe('PostgreSQL SQL compatibility', () => {
  it('preserves camelCase identifiers and numbers only actual placeholders', () => {
    expect(postgresSql("SELECT isActive FROM apiKeys WHERE key = ? AND name = '?' -- ?\n", 'app'))
      .toBe('SELECT "isActive" FROM "app"."apiKeys" WHERE "key" = $1 AND "name" = \'?\' -- ?\n');
    expect(postgresSql("SELECT 'REAL' FROM kv", 'app')).toBe("SELECT 'REAL' FROM \"app\".\"kv\"");
  });
  it('converts imported rows to non-destructive upserts', () => {
    expect(postgresSql('INSERT OR REPLACE INTO apiKeys(id, key, isActive) VALUES(?, ?, ?)', 'app'))
      .toBe('INSERT INTO "app"."apiKeys"("id", "key", "isActive") VALUES($1, $2, $3) ON CONFLICT ("id") DO UPDATE SET "key" = excluded."key", "isActive" = excluded."isActive"');
    expect(postgresSql("INSERT OR REPLACE INTO kv(scope, key, value) VALUES('pricing', ?, ?)", 'app'))
      .toContain('ON CONFLICT ("scope", "key") DO UPDATE SET "value" = excluded."value"');
  });
  it('translates identity IDs and floating-point costs in the schema', () => {
    const sql = postgresSql(buildCreateTableSql('usageHistory', TABLES.usageHistory), 'app');
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    expect(sql).toContain('"cost" DOUBLE PRECISION DEFAULT 0');
  });
  it('rejects unsafe schema names and SQLite filesystem operations', () => {
    expect(() => validateSchema('app"; DROP SCHEMA public')).toThrow();
    expect(() => postgresSql('PRAGMA journal_mode=WAL', 'app')).toThrow('SQLite-only');
  });
});
